/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheContact: typeof import('./components/TheContact.vue')['default']
    TheContactList: typeof import('./components/TheContactList.vue')['default']
    TheContacts: typeof import('./components/TheContacts.vue')['default']
    TheConversation: typeof import('./components/TheConversation.vue')['default']
    'TheConversation.vueCreator': typeof import('./components/TheConversation.vueCreator.vue')['default']
    TheConversationCreator: typeof import('./components/TheConversationCreator.vue')['default']
    TheConversationList: typeof import('./components/TheConversationList.vue')['default']
    TheConversations: typeof import('./components/TheConversations.vue')['default']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheHeader: typeof import('./components/TheHeader.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
    TheKey: typeof import('./components/TheKey.vue')['default']
    TheKeyGenerator: typeof import('./components/TheKeyGenerator.vue')['default']
    TheKeyImportator: typeof import('./components/TheKeyImportator.vue')['default']
    TheLogin: typeof import('./components/TheLogin.vue')['default']
    TheMessage: typeof import('./components/TheMessage.vue')['default']
    TheMessageList: typeof import('./components/TheMessageList.vue')['default']
    ThePGP: typeof import('./components/ThePGP.vue')['default']
    ThePGPGenerator: typeof import('./components/ThePGPGenerator.vue')['default']
    TheRegister: typeof import('./components/TheRegister.vue')['default']
  }
}
