name: Raspberry Pi Deployment Pipeline

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Archive files
        run: touch package.tar.gz && tar -czvf package.tar.gz --exclude=cypress --exclude=test --exclude=package.tar.gz .

      - name: Push archive to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.RASPI_SSH_HOST }}
          username: ${{ secrets.RASPI_SSH_USERNAME }}
          password: ${{ secrets.RASPI_SSH_KEY }}
          port: ${{ secrets.RASPI_SSH_PORT }}
          source: package.tar.gz
          target: Documents/PROG/cerberes/front_end

      - name: Unpack files on server and run it
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.RASPI_SSH_HOST }}
          username: ${{ secrets.RASPI_SSH_USERNAME }}
          password: ${{ secrets.RASPI_SSH_KEY }}
          port: ${{ secrets.RASPI_SSH_PORT }}
          script: |
            set -e
            cd Documents/PROG/cerberes/front_end
            tar -xzvf package.tar.gz
            docker buildx build . -t cerberes_front:latest
            cd
            pm2 start pm2.config.js
          timeout-minute: 20
